### ISSUE TITLE
Fix list of supported properties

### ISSUE THREAD

**Issue by brigand** [brigand/react-style-proptype#1]
At least flex properties are missing.

**Comment by brigand** [comment]
@radubrehar I updated it to use mdn's list of css properties, and naively supports vendor prefixes for all properties.

**Comment by dweldon** [comment]
Am I crazy or is this list missing `fontWeight`?

**Comment by brigand** [comment]
Nope, definitely not crazy. I'll fix it.

**Comment by brigand** [comment]
Looks like a lot of stuff has changed on mdn. I updated the full list. Published as 1.2.0.

**Comment by dweldon** [comment]
Thanks for the quick fix! This is a really useful package now that `react/forbid-prop-types` is in common use.
