### ISSUE TITLE
Remove code in production build

### ISSUE THREAD

**Issue by damusnet** [brigand/react-style-proptype#10]
Hi,

Does this package support the removal of its own code in production builds, like the original prop-types do? An initial analysis tells me that it doesn't but maybe I'm missing something here.

Thanks for your help

**Comment by brigand** [comment]
@damusnet prop-types aren't automatically removed in production builds. React does skip calling the prop-types functions in production.

You can use [babel-plugin-transform-react-remove-prop-types](https://www.npmjs.com/package/babel-plugin-transform-react-remove-prop-types) with the `additionalLibraries` and the `removeImport` options.

**Comment by brigand** [comment]
@damusnet I added instructions to the readme. Please try them out and let me know if it works for you.

**Comment by damusnet** [comment]
Hi @brigand 

Thank you so much for your answer. It works perfectly!
