### ISSUE TITLE
originalConsoleError is not defined

### ISSUE THREAD

**Issue by akv23** [brigand/react-style-proptype#3]
getting originalConsoleError is not defined error in Chrome(Version 52.0.2743.82 (64-bit)
). Firefox its working fine

**Comment by leinonen** [comment]
Same problem using phantomjs-prebuilt@^2.1.7

**Comment by brigand** [comment]
Thanks for the report. I put it in the wrong file by mistake (should have been in the test file). I removed it. Published as 1.3.2
