### ISSUE TITLE
ES6 rest-spread is published without transpiling

### ISSUE THREAD

**Issue by IanVS** [brigand/react-style-proptype#4]
The recent update to `1.3.0` has broken our build because we do not run our dependencies through babel, and https://github.com/brigand/react-style-proptype/commit/fb6466c6a7a942029f601fbde130a967a2b6b8d4#diff-1fdf421c05c1140f6d71444ea2b27638R5 uses new ES6 syntax that Uglify.js does not understand.  Is there any chance you can either compile down to ES5 and publish that, or use an ES5 syntax?  We'd be very grateful!

**Comment by brigand** [comment]
Oops, sorry. Fixed in 1.3.1.

**Comment by IanVS** [comment]
Thanks.  It looks like there's another issue on this piece of code, too (https://github.com/brigand/react-style-proptype/issues/3).  Why do you need to override console.error?  It seems dangerous.

**Comment by IanVS** [comment]
Ah, I see your response on the other issue.  Thanks!
